import React, { useEffect, useMemo } from "react"
import { PATHS } from "@directory-builder/core/utils"
import { federationTtl } from "./instanceData.js"
import { loadVocabulary } from "./loadVocabulary.js"
import { vocabularyTables, vocabularyTablesCsv } from "./vocabularyTables.js"
import { highlightTurtle } from "./highlightTurtle.js"
import "prismjs/themes/prism-okaidia.css"

const vocabulary = await loadVocabulary(federationTtl, async (path) => {
    const response = await fetch(`${import.meta.env.BASE_URL}${path}`).catch(() => null)
    if (!response?.ok || response.headers.get("content-type")?.includes("text/html")) return ""
    return response.text()
})
const highlighted = highlightTurtle(vocabulary)
const schemas = await vocabularyTables(vocabulary)
const schemaId = (iri) => `vocabulary-${encodeURIComponent(iri)}`
const exampleValuesLink = (schema, field) => `#/query?${new URLSearchParams({
    query: `SELECT DISTINCT ?value WHERE {
    ?entry a <${schema.classIri}> ;
        <${field.predicate}> ?value .
}`,
    run: "1",
})}`

export default function Vocabulary() {
    const downloadUrl = useMemo(() => URL.createObjectURL(new Blob([vocabulary], { type: "text/turtle;charset=utf-8" })), [])
    useEffect(() => () => URL.revokeObjectURL(downloadUrl), [downloadUrl])

    return (
        <div className="page vocabulary-page">
            <h1>Target vocabulary</h1>
            <section className="vocabulary-section" aria-labelledby="vocabulary-tables-heading">
                <h2 id="vocabulary-tables-heading">Schema tables</h2>
                <p>These tables are generated by querying the Turtle document below.
                    Click a field to open a query for example values in a new tab.</p>
                <p><a href={`data:text/csv;charset=utf-8,${encodeURIComponent(vocabularyTablesCsv(schemas))}`}
                    download="target-vocabulary.csv">Download tables as CSV</a></p>
                {schemas.map((schema) => (
                    <section className="vocabulary-schema" id={schemaId(schema.iri)} key={schema.iri}>
                        <h3>{schema.label} <code>{schema.className}</code></h3>
                        <div className="vocabulary-table-wrap">
                            <table aria-label={`${schema.label} fields`}>
                                <thead><tr><th scope="col">Field</th><th scope="col">Expected value</th></tr></thead>
                                <tbody>{schema.fields.map((field) => (
                                    <tr key={field.iri}>
                                        <th scope="row"><a href={exampleValuesLink(schema, field)} target="_blank" rel="noopener noreferrer"
                                            title={`Show example values for ${field.predicate} (opens in a new tab)`}>
                                            <code>{field.predicateName}</code>
                                        </a></th>
                                        <td>{field.values.map((part, i) => typeof part === "string" ? part : part.schema
                                            ? <button className="vocabulary-schema-link" key={i} onClick={() => document.getElementById(schemaId(part.schema))?.scrollIntoView({ block: "start" })}>{part.label}</button>
                                            : <span key={i}>{part.label}</span>)}</td>
                                    </tr>
                                ))}</tbody>
                            </table>
                        </div>
                        {!schema.fields.length && <p>No fields declared.</p>}
                    </section>
                ))}
            </section>
            <section className="vocabulary-section" aria-labelledby="vocabulary-turtle-heading">
                <h2 id="vocabulary-turtle-heading">Turtle</h2>
                <p>Generated from <code>federation.ttl</code>, this file defines the fields and validation rules.</p>
                <p><a href={downloadUrl} download={PATHS.targetVocabulary.split("/").pop()}>Download target-vocabulary.ttl</a></p>
                <pre className="language-turtle">
                    <code className="language-turtle" dangerouslySetInnerHTML={{ __html: highlighted }} />
                </pre>
            </section>
        </div>
    )
}
